data: online
dataset: src/main/resources/streams.csv
resultPath: result/result.json
keyPath: blacknut-analytics-7488e0e6d73d.json
testPath: tests.json
nbUserPerFile: 10
nbRecommendation: 5
configs:
- mf/config79.yml
- ibknn/config0.yml
- ibknn/config2.yml
- itemavg
- itemuseravg
normalize: false
binarize: false
