data: local
dataset: src/main/resources/streams.csv
resultPath: src/main/resources/results/result.json
keyPath: src/main/resources/blacknut-analytics-7488e0e6d73d.json
testPath: tests.json
nbUserPerFile: 1000
nbRecommendation: 10
configs:
- random
- itemavg
- ubknn/config0.yml
normalize: false
binarize: false
nruns: 1
threshold: 3
r: 5
folds: 5
strategies:
- trainingitems
doIREval: true
doTimeEval: false
doPredEval: true
